---

- name: To install lamp
  apt: 
    name: "{{item}}"apache2 
    state: present
    update_cache: yes
  with_items:
    - apache2
    - libapache2-mod-php  
    - phpmyadmin
    - mysql-client
    - python-mysqldb
    - php-mysql
    - mysql-server
  notify:
    - mysql_restart_debian

- name: Mysql_Secure_Installation
  include: mysql_secure_installation_debian.yml

    
- name: Install Hello World PHP Script
  copy: src=index.php dest=/var/www/html/index.php mode=0644

- name: Install Hello World PHP Script with database
  copy: src=db.php dest=/var/www/html/db.php mode=0644

- name: To configure site
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf

- name: To configure site 2
  copy: src=apache.conf dest=/etc/phpmyadmin/apache.conf
  notify:
    - apache_restart_debian
    - mysql_restart_debian

