---
# tasks file for lamp
- name: To install lamp on Ubuntu
  include: debian.yml
  when:
    ansible_os_family == 'Debian'

- name: To install lamp on RedHat
  include: redhat.yml
  when:
    ansible_os_family == 'RedHat'

