---
- name: To get MySql Repo
  get_url:
    url: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
    dest: /root

- name: To Intsall LAMP
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - epel-release
    - httpd
    - /root/mysql-community-release-el7-5.noarch.rpm
    - mysql-community-server
    - mysql-community-client
    - MySQL-python
    - php-bcmath
    - php-cli
    - php-common
    - php-dba
    - php-devel
    - php-embedded
    - php-enchant
    - php-fpm
    - php-gd
    - php-mysql
    - php
    - phpmyadmin
  notify: 
    - start_httpd
    - start_mysql

- name: To configure MySql
  include: mysql_secure_installation_redhat.yml
  notify:
    - start_mysql

- name: To copy file of info
  copy: src=info.php dest=/var/www/html/info.php
  notify:
    - start_httpd

- name: To copy phpMyAdmin
  template: src=phpMyAdmin.conf.j2 dest=/etc/httpd/conf.d/phpMyAdmin.conf
  notify:
    - start_httpd
    - start_mysql

