---

- name: To get wordpress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /opt/
    remote_src: yes

- name: To create wordpress db user
  include: my.yml

- name: Tp copy config file
  template: src=wp-config.php.j2 dest=/opt/wordpress/wp-config.php

- name: To create upgrade directory
  file: path=/opt/wordpress/wp-content/upgrade state=directory

- name: To copy contents of wordpress
  shell: cp -a /opt/wordpress/. /var/www/html

- name: To add database settings
  template: src=wp-config.php.j2 dest=/var/www/html/wp-config.php
