---
# handlers file for lamp

- name: apache_restart_debian
  service: name=apache2 state=restarted enabled=true

- name: mysql_restart_debian
  service: name=mysql state=started enabled=true

- name: start_mysql
  service: name=mysqld state=restarted enabled=true
  
- name: start_httpd
  service: name=httpd state=restarted enabled=true


